<?php


namespace PhpCpm\IpAddress;


class ChinaProvince extends LocationBaseHandler
{
    static $fullName = [
        "上海市" => "上海",
        "云南省" => "云南",
        "内蒙古自治区" => "内蒙古",
        "北京市" => "北京",
        "台湾省" => "台湾",
        "吉林省" => "吉林",
        "四川省" => "四川",
        "天津市" => "天津",
        "宁夏回族自治区" => "宁夏",
        "安徽省" => "安徽",
        "山东省" => "山东",
        "山西省" => "山西",
        "广东省" => "广东",
        "广西壮族自治区" => "广西",
        "新疆维吾尔自治区" => "新疆",
        "江苏省" => "江苏",
        "江西省" => "江西",
        "河北省" => "河北",
        "河南省" => "河南",
        "浙江省" => "浙江",
        "海南省" => "海南",
        "湖北省" => "湖北",
        "湖南省" => "湖南",
        "澳门特别行政区" => "澳门",
        "甘肃省" => "甘肃",
        "福建省" => "福建",
        "西藏自治区" => "西藏",
        "贵州省" => "贵州",
        "辽宁省" => "辽宁",
        "重庆市" => "重庆",
        "陕西省" => "陕西",
        "青海省" => "青海",
        "香港特别行政区" => "香港",
        "黑龙江省" => "黑龙江",
    ];

    static $enName = [
        "hong kong" => "香港",
        "taipei" => "台湾",
        "new taipei" => "台湾",
        "shanghai" => "上海",
        "yunnan" => "云南",
        "neimenggu" => "内蒙古",
        "nei mongol" => "内蒙古",
        "inner mongolia" => "内蒙古",
        "inner mongolia autonomous region" => "内蒙古",
        "beijing" => "北京",
        "peking" => "北京",
        "taiwan" => "台湾",
        "jilin" => "吉林",
        "sichuan" => "四川",
        "tianjin" => "天津",
        "ningxia" => "宁夏",
        "anhui" => "安徽",
        "shandong" => "山东",
        "shanxi" => "山西",
        "guangdong" => "广东",
        "guangxi" => "广西",
        "xinjiang" => "新疆",
        "jiangsu" => "江苏",
        "jiangxi" => "江西",
        "hebei" => "河北",
        "henan" => "河南",
        "zhejiang" => "浙江",
        "hainan" => "海南",
        "hubei" => "湖北",
        "hunan" => "湖南",
        "aomen" => "澳门",
        "macau" => "澳门",
        "gansu" => "甘肃",
        "fujian" => "福建",
        "xizang" => "西藏",
        "tibet" => "西藏",
        "guizhou" => "贵州",
        "liaoning" => "辽宁",
        "chongqing" => "重庆",
        "shaanxi" => "陕西",
        "qinghai" => "青海",
        "hongkong" => "香港",
        "xianggang" => "香港",
        "heilongjiang" => "黑龙江",
    ];
}